---
name: Testing for cpm-cpanfile-snapshot

on:
  pull_request:
    paths:
      - ".github/**"
      - "bin/**"
    branches: ["*"]
  push:
    paths:
      - ".github/**"
      - "bin/**"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: shogo82148/actions-setup-perl@22423f01bde48fb88785c007e3166fbbbd8e892a # v1.34.0
        with:
          perl-version: latest
      - name: test to cpm-cpanfile-snapshot
        run: |
          prove -vr bin/cpm-cpanfile-snapshot
